# Generated by Django 5.2.12 on 2026-04-09 16:15

import resume_analyzer.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=resume_analyzer.security.secure_resume_upload_path),
        ),
    ]
